# Server Configuration
server.port=8081

# MySQL Connection (As per assignment RDBMS requirement [cite: 16])
spring.datasource.url=jdbc:mysql://localhost:3306/media_qa_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Sau@123

# Hibernate & JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Google Gemini API Key (For LangChain4j & AI Summarization [cite: 13, 7])
google.gemini.key=AIzaSyCEVsPIEi7s3Pn4999UP1Yc-x5h9xTjWSQ

# Deepgram API Key (For Audio/Video Transcription )
deepgram.api.key=044b298c587c970058660711cd9732dfa46f0164

# File Upload Settings (Required for PDF/Audio/Video [cite: 5])
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB