name: Java CI/CD Final

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test
        run: |
          cd backend
          # Pehle project install karenge taaki symbols mil jayein
          mvn clean install -DskipTests
          # Ab tests chalayenge coverage ke liye
          mvn test jacoco:report