# Sirf Testing ke liye H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=Sau@123
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Mock Keys (Tests ko chalne ke liye chahiye)
google.gemini.key=mock-key
deepgram.api.key=mock-key